//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityView
    {
        public Nullable<int> RelatedUserId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> AnnouncementId { get; set; }
        public string activityContent { get; set; }
        public string activityAction { get; set; }
        public int activityId { get; set; }
        public System.DateTime activityDatetime { get; set; }
    }
}
