//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcements
    {
        public int annId { get; set; }
        public string annTitle { get; set; }
        public string annContent { get; set; }
        public System.DateTime annPublishedDate { get; set; }
        public int annUserId { get; set; }
        public Nullable<System.DateTime> annUpdatedDate { get; set; }
        public Nullable<int> annUpdateUserId { get; set; }
        public bool annIsActive { get; set; }
    
        public virtual Users User { get; set; }
    }
}
