//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int cId { get; set; }
        public string cContent { get; set; }
        public System.DateTime cInsertedDate { get; set; }
        public int cProjectId { get; set; }
        public int cUserId { get; set; }
        public Nullable<System.DateTime> cUpdateDate { get; set; }
        public bool cIsActive { get; set; }
    
        public virtual Projects Project { get; set; }
        public virtual Users User { get; set; }
    }
}
