//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int EventId { get; set; }
        public Nullable<int> EventProjectId { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
        public System.DateTime EventDate { get; set; }
        public System.DateTime EventInsertedDate { get; set; }
        public Nullable<System.DateTime> EventUpdateDate { get; set; }
        public string EventFriendlyUrl { get; set; }
        public string EventLocation { get; set; }
    
        public virtual Projects Project { get; set; }
    }
}
