//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int logId { get; set; }
        public string logException { get; set; }
        public string logTrace { get; set; }
        public string logCurrentClass { get; set; }
        public System.DateTime logDatetime { get; set; }
    }
}
