//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLookup
    {
        public int fileLookUpId { get; set; }
        public int fileLookUpUserId { get; set; }
        public int fileLookUpProjectId { get; set; }
        public string fileLookUpPath { get; set; }
        public Nullable<System.DateTime> fileLookUpDatetime { get; set; }
    
        public virtual Projects Project { get; set; }
        public virtual Users User { get; set; }
    }
}
