//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.Comments = new HashSet<Comments>();
            this.UserProjects = new HashSet<UserProjects>();
            this.FileLookups = new HashSet<FileLookup>();
            this.Events = new HashSet<Events>();
        }
    
        public int prId { get; set; }
        public string prDescription { get; set; }
        public string prTitle { get; set; }
        public System.DateTime prInsertDate { get; set; }
        public System.DateTime prUpdateDate { get; set; }
        public int prTypeId { get; set; }
        public string prSubject { get; set; }
        public string prKeywords { get; set; }
        public System.DateTime prStartDate { get; set; }
        public System.DateTime prEndDate { get; set; }
        public int prCatId { get; set; }
        public bool prIsPaper { get; set; }
        public string prExtraInfo { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ProjectTypes ProjectTypes { get; set; }
        public virtual ICollection<UserProjects> UserProjects { get; set; }
        public virtual ICollection<FileLookup> FileLookups { get; set; }
        public virtual ICollection<Events> Events { get; set; }
        public virtual ProjectCategories Category { get; set; }
    }
}
