//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextConstants
    {
        public TextConstants()
        {
            this.TextConstantValues = new HashSet<TextConstantValues>();
        }
    
        public int TextConstId { get; set; }
        public string TextConstName { get; set; }
        public System.DateTime TextConstDatetime { get; set; }
    
        public virtual ICollection<TextConstantValues> TextConstantValues { get; set; }
    }
}
