//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextConstantValues
    {
        public int tConstValConstId { get; set; }
        public int tConstValLangId { get; set; }
        public string tConstValValue { get; set; }
    
        public virtual TextConstants TextConstant { get; set; }
    }
}
