//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Comments = new HashSet<Comments>();
            this.UserProjects = new HashSet<UserProjects>();
            this.Announcements = new HashSet<Announcements>();
            this.FileLookup = new HashSet<FileLookup>();
        }
    
        public int userId { get; set; }
        public string userEmail { get; set; }
        public string userName { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string userPassword { get; set; }
        public string userSalt { get; set; }
        public System.DateTime userRegistrationDate { get; set; }
        public System.DateTime userLastVisitDate { get; set; }
        public int userGroupId { get; set; }
        public string userImage { get; set; }
        public Nullable<bool> userIsNew { get; set; }
        public Nullable<bool> userIsAnonymous { get; set; }
        public bool userIsActive { get; set; }
        public Nullable<System.DateTime> userVisitDate { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual UserGroups UserGroups { get; set; }
        public virtual ICollection<UserProjects> UserProjects { get; set; }
        public virtual ICollection<Announcements> Announcements { get; set; }
        public virtual ICollection<FileLookup> FileLookup { get; set; }
    }
}
